[tasks.ast-array-of]
run = [
  "ast-grep scan --rule ~/workspace/vinzloh/pi-co/rules/array-of/literal-array-includes.yml . -U",
  "ast-grep scan --rule ~/workspace/vinzloh/pi-co/rules/array-of/add-arrayof-import.yml . -U",
]

[tasks.ast-react-namespace]
run = [
  "ast-grep scan --rule ~/workspace/vinzloh/pi-co/rules/react-namespace/no-namespace-calls.yml . -U",
  "ast-grep scan --rule ~/workspace/vinzloh/pi-co/rules/react-namespace/no-namespace-import.yml . -U",
  "ast-grep scan --rule ~/workspace/vinzloh/pi-co/rules/react-namespace/no-unused-import.yml . -U",
]
